{"name": "test_call_api_with_timeout_error", "status": "passed", "description": "测试超时错误", "start": 1761614695584, "stop": 1761614695585, "uuid": "62d21e19-7abc-4437-bce5-30c60aa2801e", "historyId": "db80233534e88bc9983b84fab09f18b9", "testCaseId": "87c2e1477f6eff2d18310506f8ad4e10", "fullName": "testcases.test_error_response.TestCallApi#test_call_api_with_timeout_error", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_error_response"}, {"name": "subSuite", "value": "TestCallApi"}, {"name": "host", "value": "DESKTOP-SQEMBVG"}, {"name": "thread", "value": "15580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_error_response"}]}